export interface HapvidaUnidade {
  nome: string;
  endereco: string;
  cidade: string;
  uf: string;
  telefone?: string;
  tipo: 'Hospital' | 'Clínica' | 'Diagnóstico' | 'Outro';
}

export const HAPVIDA_UNIDADES: HapvidaUnidade[] = [
  // ─── ALAGOAS (AL) ───────────────────────────────────────────────────────────
  { nome: 'Clínica Fernandes Lima', endereco: 'Avenida Fernandes Lima, 139 - Farol', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Clínica' },
  { nome: 'Clínica Oldemburgo Paranhos', endereco: 'Rua Oldemburgo da Silva Paranhos, 55 - Farol', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Clínica' },
  { nome: 'Diagnóstico Hospital Maceió', endereco: 'Avenida Presidente Getúlio Vargas, 300 - Serraria', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Maceió', endereco: 'Rua Oldemburgo da Silva Paranhos, 55 - Farol', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Diagnóstico' },
  { nome: 'Hospital e Maternidade Maceió', endereco: 'Avenida Presidente Getúlio Vargas, 300 - Serraria', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Hospital' },
  { nome: 'Unidade de Autorização, Cadastro e Biometria Maceió', endereco: 'R. Comendador Palmeira, 623 - Farol', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Outro' },

  // ─── AMAZONAS (AM) ──────────────────────────────────────────────────────────
  { nome: 'Clínica Duque de Caxias', endereco: 'Rua Duque de Caxias, 1905 - Praça 14 de Janeiro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
  { nome: 'Clínica Flores', endereco: 'Avenida Torquato Tapajós, 5320 - Flores', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
  { nome: 'Clínica Parque Dez', endereco: 'Avenida Tancredo Neves, 1324 - Parque 10 de Novembro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
  { nome: 'Clínica Silves', endereco: 'Avenida Silves, 1658 - Crespo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
  { nome: 'Clínica Vieiralves', endereco: 'Av. João Valério, 123 - São Geraldo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
  { nome: 'Clínica Zona Leste', endereco: 'Rua Autaz Mirim, 7602 - Tancredo Neves', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
  { nome: 'Hapvida Diagnóstico Adrianópolis', endereco: 'Rua Teresina, 296 - Adrianópolis', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Aparecida', endereco: 'Rua Alexandre Amorin, 470 - Aparecida', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Centro', endereco: 'Rua dos Tapajós, 561 - Centro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnósticos Rio Negro', endereco: 'Rua dos Tapajós, 561 - Centro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnósticos Zona Leste', endereco: 'Avenida Altaz Mirim, 7602 - Tancredo Neves', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
  { nome: 'Hospital e Maternidade Rio Amazonas', endereco: 'Rua Belém, 801 - São Francisco', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
  { nome: 'Hospital Nilton Lins', endereco: 'Av. Prof. Nilton Lins, 3259 - Flores', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
  { nome: 'Hospital Pediátrico Rio Solimões', endereco: 'Av. Álvaro Maia, 1131 - Presidente Vargas', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
  { nome: 'Hospital Rio Negro', endereco: 'Rua dos Tapajós, 561 - Centro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
  { nome: 'Hospital São Lucas', endereco: 'Rua Alexandre Amorim, 470 - Aparecida', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
  { nome: 'Pronto Atendimento Cidade Nova', endereco: 'Av. Camapuã, 695 - Cidade Nova', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
  { nome: 'Pronto Atendimento Distrito', endereco: 'Avenida Buriti, 3727 - Distrito Industrial I', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
  { nome: 'Qualivida Cachoeirinha', endereco: 'Avenida Tefé, 625 - Cachoeirinha', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
  { nome: 'Qualivida Manaus', endereco: 'Av. João Valério, 123 - São Geraldo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
  { nome: 'Unidade de Autorização Manaus', endereco: 'Rua João Valério, 85 - São Geraldo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
  { nome: 'Unidade de Autorização, Cadastro e Biometria Manaus', endereco: 'Av. João Valério, 606 - São Geraldo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
  { nome: 'Unidade de Biometria e Autorização', endereco: 'Avenida Duque de Caxias, 1905 - Praça 14 de Janeiro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },

  // ─── BAHIA (BA) ─────────────────────────────────────────────────────────────
  { nome: 'Clínica Alagoinhas', endereco: 'Travessa Dr. Dantas Bião, 254-284 - Jardim Petrolar', cidade: 'Alagoinhas - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Diagnóstico Alagoinhas', endereco: 'Tv. Dr. Dantas Bião, 254-284 - Alagoinhas Velha', cidade: 'Alagoinhas - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hospital e Maternidade Cetro', endereco: 'Rua Elvira Dórea, 1 - Centro', cidade: 'Alagoinhas - BA', uf: 'BA', tipo: 'Hospital' },
  { nome: 'Unidade de Autorização Alagoinhas', endereco: 'Travessa Dantas Bião, 254 - Alagoinhas Velha', cidade: 'Alagoinhas - BA', uf: 'BA', tipo: 'Outro' },
  { nome: 'Clínica Camaçari', endereco: 'Av. Dr. Manoel Mercês, S/n - Mangueiral', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Diagnóstico Dois de Maio', endereco: 'Rua Dois de Maio, 7 - Centro', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Hospital Semed', endereco: 'Rua Francisco Drumond, 238 - Centro', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hospital Semed', endereco: 'Rua Francisco Drumond, 238 - Centro', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Hospital' },
  { nome: 'Unidade de Biometria Camaçari', endereco: 'Av. Dr. Manoel Mercês, S/n - Mangueiral', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Outro' },
  { nome: 'Clínica Cidade de Candeias', endereco: 'BA 523, 588 - Urbis I', cidade: 'Candeias - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Hapvida Diagnósticos Centro de Santana', endereco: 'Rua Agripo Ramos, 86 - Centro', cidade: 'Catu - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Centro Cruz das Almas', endereco: 'Avenida Mata Pereira - Térreo, 413 - Centro', cidade: 'Cruz das Almas - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Dias D\'Ávila', endereco: 'Rua da Mangueira, 64 - Centro', cidade: 'Dias D\'Ávila - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Clínica Feira de Santana', endereco: 'Rua Visconde do Rio Branco, 555 - Centro', cidade: 'Feira de Santana - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Hapvida Diagnóstico Hospital Francisca de Sande', endereco: 'Rua Professora Edelvira de Oliveira, 140 - Centro', cidade: 'Feira de Santana - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hospital Francisca de Sande', endereco: 'Rua Professora Edelvira de Oliveira, 140 - Centro', cidade: 'Feira de Santana - BA', uf: 'BA', tipo: 'Hospital' },
  { nome: 'Unidade de Cadastro e Biometria Feira de Santana', endereco: 'Rua Visconde do Rio Branco, 555 - Centro', cidade: 'Feira de Santana - BA', uf: 'BA', tipo: 'Outro' },
  { nome: 'Clínica Lauro de Freitas II', endereco: 'BA 099, 2077 - Centro', cidade: 'Lauro de Freitas - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Hapvida Diagnóstico Hospital Lauro de Freitas', endereco: 'BA 099, 2077 - Centro', cidade: 'Lauro de Freitas - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hospital Lauro de Freitas', endereco: 'BA 099, N 2077 - Centro', cidade: 'Lauro de Freitas - BA', uf: 'BA', tipo: 'Hospital' },
  { nome: 'Unidade de Autorização Lauro de Freitas', endereco: 'Avenida Santos Dumont, 1529 - Centro', cidade: 'Lauro de Freitas - BA', uf: 'BA', tipo: 'Outro' },
  { nome: 'Clínica Amaralina', endereco: 'Rua Fernando de Noronha, 98 - Amaralina', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Clínica Cajazeiras', endereco: 'Shopping Cajazeiras, Piso G2, Entrada Coqueiro Grande, 1361 - Cajazeiras', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Clínica Costa Azul', endereco: 'Rua Adelaide Fernandes da Costa, 903 OT - Costa Azul', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Clínica Dique', endereco: 'Av. Vasco da Gama, 206 - Federação', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Clínica Garibaldi', endereco: 'Avenida Anita Garibaldi, 391 - Ondina', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Clínica Parque Bela Vista', endereco: 'Avenida Santiago de Compostela, 222 - Parque Bela Vista', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Clínica Pituba', endereco: 'Rua Rio de Janeiro, 253 - Pituba', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Clínica Pituba II', endereco: 'Rua Pará, 301 - Pituba', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Clínica Uruguai', endereco: 'Rua do Uruguay, 852 - Uruguai', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Clínica Vasco da Gama', endereco: 'Avenida Vasco da Gama, 309 - Federação', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
  { nome: 'Hapvida Diagnóstico Cajazeiras', endereco: 'Rua da Paz do Coqueiro Grande, 2023 - Cajazeiras', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Hospital Teresa de Lisieux', endereco: 'Avenida Antônio Carlos Magalhães, 2408 - Itaigara', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Lucaia', endereco: 'Avenida Juracy Magalhães, 1122 - Rio Vermelho', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Uruguai', endereco: 'Rua do Uruguay, 852 - Uruguai', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Vasco da Gama', endereco: 'Av. Vasco da Gama, 309 - Vasco da Gama', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Hospital e Maternidade Teresa de Lisieux', endereco: 'Avenida Antônio Carlos Magalhães, 2408 - Itaigara', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Hospital' },
  { nome: 'Laboratório Dique do Tororó', endereco: 'Av. Vasco da Gama, 206 - Federação', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Pronto Atendimento Cajazeiras', endereco: 'Rua da Paz do Coqueiro Grande, 2023 - Cajazeiras', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Outro' },
  { nome: 'Pronto Atendimento Uruguai', endereco: 'Rua do Uruguay, 852 - Uruguai', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Outro' },
  { nome: 'Unidade de Autorização, Cadastro e Biometria Salvador', endereco: 'Rua Frederico Simões, 98 - Caminho das Árvores', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Outro' },
  { nome: 'Diagnóstico Quinta do Inglês', endereco: 'Rua A-2, Ed. Master Térreo - Lot. Quinta do Inglês', cidade: 'Santo Antônio de Jesus - BA', uf: 'BA', tipo: 'Diagnóstico' },
  { nome: 'Clínica e Diagnóstico Simões Filho', endereco: 'Av. Luiz Eduardo Magalhães, 187 - Centro', cidade: 'Simões Filho - BA', uf: 'BA', tipo: 'Clínica' },

  { nome: 'Clínica Antônio Sales', endereco: 'Av. Antônio Sales, 2238 - Dionísio Torres', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Barão de Studart', endereco: 'Av. Barão de Studart, 2260 - Dionísio Torres', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Conjunto Ceará', endereco: 'Av. Ministro Albuquerque Lima, 1421 - Conjunto Ceará 3ª etapa', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Dom Manuel', endereco: 'Avenida Dom Manuel, 1395 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Francisco Sá', endereco: 'Av. Francisco Sá, 5271 - Álvaro Weyne', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Heráclito Graça', endereco: 'Av. Heráclito Graça, 500b - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Isaac Newton', endereco: 'Rua Visconde de Mauá, 1593 - Meireles', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Joaquim Távora', endereco: 'Avenida Antônio Sales, 60 - Joaquim Távora', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica José Walter', endereco: 'Avenida João Araújo de Lima, 591 - José Walter', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Lobo Filho', endereco: 'Rua João Lobo Filho, 72 - Fátima', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Messejana', endereco: 'Rua Tenente Jurandi Alencar, 234 - Messejana', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Monte Castelo', endereco: 'R. Ribeiro da Silva, 761 - São Gerardo', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Montese', endereco: 'Av. Gomes de Matos, 1737 - Montese', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Pereira Filgueiras', endereco: 'Rua Pereira Filgueiras, 825 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Rodrigues Júnior', endereco: 'Rua Pereira Filgueiras, 825 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica Santos Dumont', endereco: 'Av. Santos Dumont, 1058 - Aldeota', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Clínica São Gerardo', endereco: 'Av. Bezerra de Menezes, 981 - São Gerardo', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Hapvida Diagnóstico Centro Fortaleza', endereco: 'Avenida Heráclito Graça, 500 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Centro Fortaleza II', endereco: 'Avenida Heráclito Graça, 100 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Conjunto Ceará', endereco: 'Av. Ministro Albuquerque Lima, 228 - Conjunto Ceará', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Joaquim Távora', endereco: 'Av. Antônio Sales, 60 - Joaquim Távora', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Mário Barreto', endereco: 'Rua São Raimundo, 1781 - Cambeba', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnóstico Parangaba', endereco: 'Av. Dr. Silas Munguba, 136 - Parangaba', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnósticos Aldeota', endereco: 'Rua Padre Valdevino, 2640 - Aldeota', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
  { nome: 'Hapvida Diagnósticos Heráclito Graça', endereco: 'Avenida Heráclito Graça, 1357 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
  { nome: 'Hospital Aldeota', endereco: 'Av. Padre Antônio Tomás, 2056 - Aldeota', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Hospital' },
  { nome: 'Hospital Antônio Prudente', endereco: 'Avenida Aguanambi, 1827 - Bairro de Fátima', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Hospital' },
  { nome: 'Hospital e Maternidade Eugênia Pinheiro', endereco: 'Av. Heráclito Graça, 500 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Hospital' },
  { nome: 'Hospital Luís França', endereco: 'Avenida Heráclito Graça, 100 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Hospital' },
  { nome: 'Clínica Padre Cícero', endereco: 'Rua Padre Cícero, 3996 - São José', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Hospital Geral e Maternidade Padre Cícero', endereco: 'Avenida Padre Cícero, 2481 - Triângulo', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Hospital' },
  { nome: 'Unidade de Autorização e Cadastro Juazeiro', endereco: 'Rua Padre Cícero, 3996 - Centro', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Outro' },
  { nome: 'Unidade de Biometria Juazeiro', endereco: 'Rua Padre Cícero, 529 - Centro', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Outro' },
  { nome: 'Unidade de Biometria Juazeiro II', endereco: 'Rua São José, 836 - Centro', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Outro' },
  { nome: 'Clínica Maracanaú', endereco: 'Avenida Parque Comercial, S/N - Distrito Industrial', cidade: 'Maracanaú - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Hapvida Diagnóstico Ana Lima', endereco: 'Avenida Parque Comercial, S/N - Pajuçara', cidade: 'Maracanaú - CE', uf: 'CE', tipo: 'Diagnóstico' },
  { nome: 'Hospital e Maternidade Ana Lima', endereco: 'Avenida Parque Comercial, S/N - Pajuçara', cidade: 'Maracanaú - CE', uf: 'CE', tipo: 'Hospital' },
  { nome: 'Unidade de Autorização Maracanaú', endereco: 'Avenida Parque Comercial S/N - Distrito Industrial', cidade: 'Maracanaú - CE', uf: 'CE', tipo: 'Outro' },
  { nome: 'Pronto Atendimento Pacajus', endereco: 'Rua Naide Costa Menezes, 525 - Centro', cidade: 'Pacajus - CE', uf: 'CE', tipo: 'Outro' },
  { nome: 'Clínica Hapvida Pecém', endereco: 'Av. Antônio Brasileiro, 131 - Pecém', cidade: 'São Gonçalo do Amarante - CE', uf: 'CE', tipo: 'Clínica' },
  { nome: 'Pronto Atendimento Pecém', endereco: 'Av. Antônio Brasileiro, 131 - Pecém', cidade: 'São Gonçalo do Amarante - CE', uf: 'CE', tipo: 'Outro' },
];

// Agrupa por estado
export const UF_LABELS: Record<string, string> = {
  AL: 'Alagoas', AM: 'Amazonas', BA: 'Bahia', CE: 'Ceará',
  GO: 'Goiás', MA: 'Maranhão', MT: 'Mato Grosso', PA: 'Pará',
  PB: 'Paraíba', PE: 'Pernambuco', PI: 'Piauí', PR: 'Paraná',
  RN: 'Rio Grande do Norte', SE: 'Sergipe', SP: 'São Paulo', TO: 'Tocantins',
};

export function getUnidadesPorUF(uf: string): HapvidaUnidade[] {
  return HAPVIDA_UNIDADES.filter(u => u.uf === uf);
}

export const UFS_DISPONIVEIS = [...new Set(HAPVIDA_UNIDADES.map(u => u.uf))].sort();
