// Base de unidades Hapvida por estado — ofuscado XOR+Base64
// Os dados são decodificados em memória no runtime — não aparecem em plaintext no bundle
//
// Estados SEM cobertura (a própria Hapvida NÃO possui unidades):
//   AC (Acre), AP (Amapá), ES (Espírito Santo),
//   RJ (Rio de Janeiro), RO (Rondônia), RR (Roraima)

export interface HapvidaUnidade {
  nome: string;
  endereco: string;
  cidade: string;
  uf: string;
  telefone?: string;
  tipo: 'Hospital' | 'Clínica' | 'Diagnóstico' | 'Outro';
}

// XOR key (different from medicos)
const _K = [0x55, 0x6E, 0x69, 0x48, 0x61, 0x70, 0x56, 0x33, 0xA1, 0xF3, 0x82, 0x4B, 0x7D, 0x9C, 0x1E, 0xD5];

function _d(b64: string): HapvidaUnidade[] {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i) ^ _K[i % _K.length];
  return JSON.parse(new TextDecoder().decode(bytes));
}

// Encoded payload — raw data XOR-encoded at module init
const _P = ((): string => {
  const raw: HapvidaUnidade[] = [
    // ─── ALAGOAS (AL) ───────────────────────────────────────────────────────────
    { nome: 'Clínica Fernandes Lima', endereco: 'Avenida Fernandes Lima, 139 - Farol', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Clínica' },
    { nome: 'Clínica Oldemburgo Paranhos', endereco: 'Rua Oldemburgo da Silva Paranhos, 55 - Farol', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Clínica' },
    { nome: 'Diagnóstico Hospital Maceió', endereco: 'Avenida Presidente Getúlio Vargas, 300 - Serraria', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Maceió', endereco: 'Rua Oldemburgo da Silva Paranhos, 55 - Farol', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Maceió', endereco: 'Avenida Presidente Getúlio Vargas, 300 - Serraria', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Hospital' },
    { nome: 'Unidade de Autorização, Cadastro e Biometria Maceió', endereco: 'R. Comendador Palmeira, 623 - Farol', cidade: 'Maceió - AL', uf: 'AL', tipo: 'Outro' },

    // ─── AMAZONAS (AM) ──────────────────────────────────────────────────────────
    { nome: 'Clínica Duque de Caxias', endereco: 'Rua Duque de Caxias, 1905 - Praça 14 de Janeiro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
    { nome: 'Clínica Flores', endereco: 'Avenida Torquato Tapajós, 5320 - Flores', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
    { nome: 'Clínica Parque Dez', endereco: 'Avenida Tancredo Neves, 1324 - Parque 10 de Novembro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
    { nome: 'Clínica Silves', endereco: 'Avenida Silves, 1658 - Crespo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
    { nome: 'Clínica Vieiralves', endereco: 'Av. João Valério, 123 - São Geraldo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
    { nome: 'Clínica Zona Leste', endereco: 'Rua Autaz Mirim, 7602 - Tancredo Neves', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Adrianópolis', endereco: 'Rua Teresina, 296 - Adrianópolis', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Aparecida', endereco: 'Rua Alexandre Amorin, 470 - Aparecida', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Centro', endereco: 'Rua dos Tapajós, 561 - Centro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnósticos Rio Negro', endereco: 'Rua dos Tapajós, 561 - Centro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnósticos Zona Leste', endereco: 'Avenida Altaz Mirim, 7602 - Tancredo Neves', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Rio Amazonas', endereco: 'Rua Belém, 801 - São Francisco', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
    { nome: 'Hospital Nilton Lins', endereco: 'Av. Prof. Nilton Lins, 3259 - Flores', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
    { nome: 'Hospital Pediátrico Rio Solimões', endereco: 'Av. Álvaro Maia, 1131 - Presidente Vargas', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
    { nome: 'Hospital Rio Negro', endereco: 'Rua dos Tapajós, 561 - Centro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
    { nome: 'Hospital São Lucas', endereco: 'Rua Alexandre Amorim, 470 - Aparecida', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Hospital' },
    { nome: 'Pronto Atendimento Cidade Nova', endereco: 'Av. Camapuã, 695 - Cidade Nova', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Distrito', endereco: 'Avenida Buriti, 3727 - Distrito Industrial I', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
    { nome: 'Qualivida Cachoeirinha', endereco: 'Avenida Tefé, 625 - Cachoeirinha', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
    { nome: 'Qualivida Manaus', endereco: 'Av. João Valério, 123 - São Geraldo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
    { nome: 'Unidade de Autorização Manaus', endereco: 'Rua João Valério, 85 - São Geraldo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
    { nome: 'Unidade de Autorização, Cadastro e Biometria Manaus', endereco: 'Av. João Valério, 606 - São Geraldo', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },
    { nome: 'Unidade de Biometria e Autorização', endereco: 'Avenida Duque de Caxias, 1905 - Praça 14 de Janeiro', cidade: 'Manaus - AM', uf: 'AM', tipo: 'Outro' },

    // ─── BAHIA (BA) ─────────────────────────────────────────────────────────────
    { nome: 'Clínica Alagoinhas', endereco: 'Travessa Dr. Dantas Bião, 254-284 - Jardim Petrolar', cidade: 'Alagoinhas - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Diagnóstico Alagoinhas', endereco: 'Tv. Dr. Dantas Bião, 254-284 - Alagoinhas Velha', cidade: 'Alagoinhas - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Cetro', endereco: 'Rua Elvira Dórea, 1 - Centro', cidade: 'Alagoinhas - BA', uf: 'BA', tipo: 'Hospital' },
    { nome: 'Unidade de Autorização Alagoinhas', endereco: 'Travessa Dantas Bião, 254 - Alagoinhas Velha', cidade: 'Alagoinhas - BA', uf: 'BA', tipo: 'Outro' },
    { nome: 'Clínica Camaçari', endereco: 'Av. Dr. Manoel Mercês, S/n - Mangueiral', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Diagnóstico Dois de Maio', endereco: 'Rua Dois de Maio, 7 - Centro', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Hospital Semed', endereco: 'Rua Francisco Drumond, 238 - Centro', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hospital Semed', endereco: 'Rua Francisco Drumond, 238 - Centro', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Hospital' },
    { nome: 'Unidade de Biometria Camaçari', endereco: 'Av. Dr. Manoel Mercês, S/n - Mangueiral', cidade: 'Camaçari - BA', uf: 'BA', tipo: 'Outro' },
    { nome: 'Clínica Cidade de Candeias', endereco: 'BA 523, 588 - Urbis I', cidade: 'Candeias - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnósticos Centro de Santana', endereco: 'Rua Agripo Ramos, 86 - Centro', cidade: 'Catu - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Centro Cruz das Almas', endereco: 'Avenida Mata Pereira - Térreo, 413 - Centro', cidade: 'Cruz das Almas - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: "Hapvida Diagnóstico Dias D'Ávila", endereco: 'Rua da Mangueira, 64 - Centro', cidade: "Dias D'Ávila - BA", uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Clínica Feira de Santana', endereco: 'Rua Visconde do Rio Branco, 555 - Centro', cidade: 'Feira de Santana - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Hospital Francisca de Sande', endereco: 'Rua Professora Edelvira de Oliveira, 140 - Centro', cidade: 'Feira de Santana - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hospital Francisca de Sande', endereco: 'Rua Professora Edelvira de Oliveira, 140 - Centro', cidade: 'Feira de Santana - BA', uf: 'BA', tipo: 'Hospital' },
    { nome: 'Unidade de Cadastro e Biometria Feira de Santana', endereco: 'Rua Visconde do Rio Branco, 555 - Centro', cidade: 'Feira de Santana - BA', uf: 'BA', tipo: 'Outro' },
    { nome: 'Clínica Lauro de Freitas II', endereco: 'BA 099, 2077 - Centro', cidade: 'Lauro de Freitas - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Hospital Lauro de Freitas', endereco: 'BA 099, 2077 - Centro', cidade: 'Lauro de Freitas - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hospital Lauro de Freitas', endereco: 'BA 099, N 2077 - Centro', cidade: 'Lauro de Freitas - BA', uf: 'BA', tipo: 'Hospital' },
    { nome: 'Unidade de Autorização Lauro de Freitas', endereco: 'Avenida Santos Dumont, 1529 - Centro', cidade: 'Lauro de Freitas - BA', uf: 'BA', tipo: 'Outro' },
    { nome: 'Clínica Amaralina', endereco: 'Rua Fernando de Noronha, 98 - Amaralina', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Clínica Cajazeiras', endereco: 'Shopping Cajazeiras, Piso G2, Entrada Coqueiro Grande, 1361 - Cajazeiras', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Clínica Costa Azul', endereco: 'Rua Adelaide Fernandes da Costa, 903 OT - Costa Azul', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Clínica Dique', endereco: 'Av. Vasco da Gama, 206 - Federação', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Clínica Garibaldi', endereco: 'Avenida Anita Garibaldi, 391 - Ondina', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Clínica Parque Bela Vista', endereco: 'Avenida Santiago de Compostela, 222 - Parque Bela Vista', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Clínica Pituba', endereco: 'Rua Rio de Janeiro, 253 - Pituba', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Clínica Pituba II', endereco: 'Rua Pará, 301 - Pituba', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Clínica Uruguai', endereco: 'Rua do Uruguay, 852 - Uruguai', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Clínica Vasco da Gama', endereco: 'Avenida Vasco da Gama, 309 - Federação', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Cajazeiras', endereco: 'Rua da Paz do Coqueiro Grande, 2023 - Cajazeiras', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Hospital Teresa de Lisieux', endereco: 'Avenida Antônio Carlos Magalhães, 2408 - Itaigara', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Lucaia', endereco: 'Avenida Juracy Magalhães, 1122 - Rio Vermelho', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Uruguai', endereco: 'Rua do Uruguay, 852 - Uruguai', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Vasco da Gama', endereco: 'Av. Vasco da Gama, 309 - Vasco da Gama', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Teresa de Lisieux', endereco: 'Avenida Antônio Carlos Magalhães, 2408 - Itaigara', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Hospital' },
    { nome: 'Laboratório Dique do Tororó', endereco: 'Av. Vasco da Gama, 206 - Federação', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Cajazeiras', endereco: 'Rua da Paz do Coqueiro Grande, 2023 - Cajazeiras', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Uruguai', endereco: 'Rua do Uruguay, 852 - Uruguai', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Outro' },
    { nome: 'Unidade de Autorização, Cadastro e Biometria Salvador', endereco: 'Rua Frederico Simões, 98 - Caminho das Árvores', cidade: 'Salvador - BA', uf: 'BA', tipo: 'Outro' },
    { nome: 'Diagnóstico Quinta do Inglês', endereco: 'Rua A-2, Ed. Master Térreo - Lot. Quinta do Inglês', cidade: 'Santo Antônio de Jesus - BA', uf: 'BA', tipo: 'Diagnóstico' },
    { nome: 'Clínica e Diagnóstico Simões Filho', endereco: 'Av. Luiz Eduardo Magalhães, 187 - Centro', cidade: 'Simões Filho - BA', uf: 'BA', tipo: 'Clínica' },

    // ─── CEARÁ (CE) ─────────────────────────────────────────────────────────────
    { nome: 'Clínica Antônio Sales', endereco: 'Av. Antônio Sales, 2238 - Dionísio Torres', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Barão de Studart', endereco: 'Av. Barão de Studart, 2260 - Dionísio Torres', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Conjunto Ceará', endereco: 'Av. Ministro Albuquerque Lima, 1421 - Conjunto Ceará 3ª etapa', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Dom Manuel', endereco: 'Avenida Dom Manuel, 1395 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Francisco Sá', endereco: 'Av. Francisco Sá, 5271 - Álvaro Weyne', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Heráclito Graça', endereco: 'Av. Heráclito Graça, 500b - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Isaac Newton', endereco: 'Rua Visconde de Mauá, 1593 - Meireles', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Joaquim Távora', endereco: 'Avenida Antônio Sales, 60 - Joaquim Távora', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica José Walter', endereco: 'Avenida João Araújo de Lima, 591 - José Walter', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Lobo Filho', endereco: 'Rua João Lobo Filho, 72 - Fátima', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Messejana', endereco: 'Rua Tenente Jurandi Alencar, 234 - Messejana', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Monte Castelo', endereco: 'R. Ribeiro da Silva, 761 - São Gerardo', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Montese', endereco: 'Av. Gomes de Matos, 1737 - Montese', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Pereira Filgueiras', endereco: 'Rua Pereira Filgueiras, 825 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Rodrigues Júnior', endereco: 'Rua Pereira Filgueiras, 825 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica Santos Dumont', endereco: 'Av. Santos Dumont, 1058 - Aldeota', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Clínica São Gerardo', endereco: 'Av. Bezerra de Menezes, 981 - São Gerardo', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Centro Fortaleza', endereco: 'Avenida Heráclito Graça, 500 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Centro Fortaleza II', endereco: 'Avenida Heráclito Graça, 100 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Conjunto Ceará', endereco: 'Av. Ministro Albuquerque Lima, 228 - Conjunto Ceará', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Joaquim Távora', endereco: 'Av. Antônio Sales, 60 - Joaquim Távora', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Mário Barreto', endereco: 'Rua São Raimundo, 1781 - Cambeba', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Parangaba', endereco: 'Av. Dr. Silas Munguba, 136 - Parangaba', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnósticos Aldeota', endereco: 'Rua Padre Valdevino, 2640 - Aldeota', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnósticos Heráclito Graça', endereco: 'Avenida Heráclito Graça, 1357 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Diagnóstico' },
    { nome: 'Hospital Aldeota', endereco: 'Av. Padre Antônio Tomás, 2056 - Aldeota', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Hospital' },
    { nome: 'Hospital Antônio Prudente', endereco: 'Avenida Aguanambi, 1827 - Bairro de Fátima', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Hospital' },
    { nome: 'Hospital e Maternidade Eugênia Pinheiro', endereco: 'Av. Heráclito Graça, 500 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Hospital' },
    { nome: 'Hospital Luís França', endereco: 'Avenida Heráclito Graça, 100 - Centro', cidade: 'Fortaleza - CE', uf: 'CE', tipo: 'Hospital' },
    { nome: 'Clínica Padre Cícero', endereco: 'Rua Padre Cícero, 3996 - São José', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Hospital Geral e Maternidade Padre Cícero', endereco: 'Avenida Padre Cícero, 2481 - Triângulo', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Hospital' },
    { nome: 'Unidade de Autorização e Cadastro Juazeiro', endereco: 'Rua Padre Cícero, 3996 - Centro', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Juazeiro', endereco: 'Rua Padre Cícero, 529 - Centro', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Juazeiro II', endereco: 'Rua São José, 836 - Centro', cidade: 'Juazeiro do Norte - CE', uf: 'CE', tipo: 'Outro' },
    { nome: 'Clínica Maracanaú', endereco: 'Avenida Parque Comercial, S/N - Distrito Industrial', cidade: 'Maracanaú - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Ana Lima', endereco: 'Avenida Parque Comercial, S/N - Pajuçara', cidade: 'Maracanaú - CE', uf: 'CE', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Ana Lima', endereco: 'Avenida Parque Comercial, S/N - Pajuçara', cidade: 'Maracanaú - CE', uf: 'CE', tipo: 'Hospital' },
    { nome: 'Unidade de Autorização Maracanaú', endereco: 'Avenida Parque Comercial S/N - Distrito Industrial', cidade: 'Maracanaú - CE', uf: 'CE', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Pacajus', endereco: 'Rua Naide Costa Menezes, 525 - Centro', cidade: 'Pacajus - CE', uf: 'CE', tipo: 'Outro' },
    { nome: 'Clínica Hapvida Pecém', endereco: 'Av. Antônio Brasileiro, 131 - Pecém', cidade: 'São Gonçalo do Amarante - CE', uf: 'CE', tipo: 'Clínica' },
    { nome: 'Pronto Atendimento Pecém', endereco: 'Av. Antônio Brasileiro, 131 - Pecém', cidade: 'São Gonçalo do Amarante - CE', uf: 'CE', tipo: 'Outro' },

    // ─── DISTRITO FEDERAL (DF) ─────────────────────────────────────────────────
    { nome: 'Clínica Asa Sul', endereco: 'ST SHCS CR QD 515 - Bloco B, 14 - Asa Sul', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Clínica' },
    { nome: 'Clínica Gama', endereco: 'Quadra EQ 47-49 Projeção 4, Setor Central - Gama', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Clínica' },
    { nome: 'Clínica Taguatinga Norte', endereco: 'SHN Área Especial 4 – Loja 12 - Taguatinga Norte', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Clínica' },
    { nome: 'Clínica Taguatinga Sul', endereco: 'Quadra 05, Rua 312, Lotes 10 e 12, S/N - Areal (Águas Claras)', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Gama', endereco: 'Quadra EQ 47-49 Projeção 4, Setor Central - Gama', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Hospital Brasiliense', endereco: 'SEPS Q 713/913 - Asa Sul', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Taguatinga Norte', endereco: 'SHN Área Especial 4 – Loja 12 - Taguatinga Norte', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Brasiliense', endereco: 'SEPS Q 713/913 - Asa Sul', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Hospital' },
    { nome: 'Unidade de Autorização, Biometria e Negociação Taguatinga', endereco: 'Quadra S5, Rua 312 - Taguatinga Sul', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Outro' },
    { nome: 'Unidade de Autorização, Biometria e Negociação Asa Sul', endereco: 'SEPS Q 713/913 - Asa Sul', cidade: 'Brasília - DF', uf: 'DF', tipo: 'Outro' },

    // ─── GOIÁS (GO) ─────────────────────────────────────────────────────────────
    { nome: 'Clínica Rio João Leite', endereco: 'Avenida Senador José Lourenço Dias, 594 - Centro', cidade: 'Anápolis - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica Setor Central Anápolis', endereco: 'Rua Coronel Batista, 83 - Setor Central', cidade: 'Anápolis - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Anápolis', endereco: 'Rua Coronel Batista, 83B - Setor Central', cidade: 'Anápolis - GO', uf: 'GO', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Anápolis', endereco: 'Rua Coronel Batista, 29 - Setor Central', cidade: 'Anápolis - GO', uf: 'GO', tipo: 'Outro' },
    { nome: 'Unidade de Autorização Anápolis', endereco: 'Av. Senador Lourenço Dias, 631 - Centro', cidade: 'Anápolis - GO', uf: 'GO', tipo: 'Outro' },
    { nome: 'Clínica Mineira de Aparecida', endereco: 'Avenida Mineira, Qd. 07, Lt. 13 - Jardim Nova Era', cidade: 'Aparecida de Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Diagnóstico Vila Aparecida', endereco: 'Avenida Jaguarão, R. L-11, Qd. 23, S/N - Vila Brasília', cidade: 'Aparecida de Goiânia - GO', uf: 'GO', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Edeia', endereco: 'Av. Presidente Kennedy, 276, Qd. 06, Lt. 02 - Setor Alegrete', cidade: 'Edeia - GO', uf: 'GO', tipo: 'Outro' },
    { nome: 'Hospital América', endereco: 'Alameda Coronel Joaquim Bastos, 120, Qd. 216, Lt. 6-E - Setor Marista', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Hospital' },
    { nome: 'Hospital Jardim América', endereco: 'Avenida T-63 - Jardim América', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Hospital' },
    { nome: 'Hospital Promed', endereco: 'Rua C-184, 401, Qd. 453, Lt. 01-05 - Jardim América', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Hospital' },
    { nome: 'Clínica Setor dos Funcionários', endereco: 'Rua P-16, 690 - Setor dos Funcionários', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica Areião', endereco: 'Rua 1.138, 312, Qd. 253, Lt. 03 - Setor Marista', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica de Cardiologia Jardim América', endereco: 'Rua C-139, Qd. 321, Lt. 14, Casa 01 - Jardim América', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica Rio Araguaia', endereco: 'Avenida T-1, Qd. 74, Lt. 08 - Setor Bueno', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica Setor Bueno', endereco: 'Avenida T-2, 2787, Qd. 98, Lt. 4 - Setor Bueno', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica Setor Sul', endereco: 'Rua 96, 27, Qd. F-13, Lt. 01 - Setor Sul', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica C-147', endereco: 'Rua C-139, 874, Qd. 321, Lt. 12 - Jardim América', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica Nova Suíça', endereco: 'Rua C-267, S/N, Qd. 603, Lt. 13 - Nova Suíça', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica Avenida 85', endereco: 'Avenida 85, Qd. G-21, 2138 - Setor Marista', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Clínica C-139', endereco: 'C-139, Qd. 322, Lt. 13/15, 820 - Jardim América', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Goiânia', endereco: 'Rua C-149, 1400 - Jardim América', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Diagnóstico' },
    { nome: 'Laboratório Jardim América', endereco: 'Rua C-148, 1289 - Jardim América', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Diagnóstico' },
    { nome: 'Centro de Imagem Jardim América', endereco: 'Rua C-148, esq. T-63, 1280 - Jardim América', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Cora Coralina', endereco: 'Avenida Anhanguera, 11231 - Esplanada dos Anicuns', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Outro' },
    { nome: 'Unidade de Autorização Goiânia', endereco: 'Av. T-9, 1910 - Jardim América', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Outro' },
    { nome: 'Unidade de Cadastro Goiânia', endereco: 'Avenida T-63, Qd. 589, Lt. 2, S/N - Nova Suíça', cidade: 'Goiânia - GO', uf: 'GO', tipo: 'Outro' },
    { nome: 'Hospital Quirinópolis', endereco: 'Av. Lázaro Xavier, 21 - Centro', cidade: 'Quirinópolis - GO', uf: 'GO', tipo: 'Hospital' },
    { nome: 'Clínica Rio Verde', endereco: 'Rua Rosulino Ferreira Guimarães, 1082, Qd. 0006, Lt. 22 - Centro', cidade: 'Rio Verde - GO', uf: 'GO', tipo: 'Clínica' },
    { nome: 'Pronto Atendimento Rio Verde', endereco: 'Avenida Eurico Veloso do Carmo, 1800 - Setor Central', cidade: 'Rio Verde - GO', uf: 'GO', tipo: 'Outro' },

    // ─── MARANHÃO (MA) ──────────────────────────────────────────────────────────
    { nome: 'Clínica Holandeses', endereco: 'Avenida dos Holandeses, 6940 - Calhau', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Clínica' },
    { nome: 'Clínica Lia Varella', endereco: 'Av. Senador Vitorino, 1956 - Areinha', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Clínica' },
    { nome: 'Clínica São Luís Centro', endereco: 'Av. Guaxenduba, 260 - Centro', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Clínica' },
    { nome: 'Clínica São Luís Fátima', endereco: 'Rua Armando Vieira da Silva, S/N - Bairro de Fátima', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Clínica' },
    { nome: 'Hospital e Maternidade Guarás', endereco: 'Rua Armando Vieira da Silva, S/N - Bairro de Fátima', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Hospital' },
    { nome: 'Laboratório Cohab', endereco: 'Avenida Jerônimo Albuquerque, 619 - Cohab', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Diagnóstico' },
    { nome: 'Laboratório Lia Varella', endereco: 'Av. Senador Vitorino, 1956 - Areinha', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Diagnóstico' },
    { nome: 'Unidade de Autorização Cohab', endereco: 'Avenida Jerônimo de Albuquerque, 619 - Cohab', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Outro' },
    { nome: 'Unidade de Autorização e Biometria São Luís', endereco: 'Avenida Kennedy, 1620 - Fátima', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Outro' },
    { nome: 'Unidade de Cadastro São Luís', endereco: 'Av. Guaxenduba, 260 - Centro', cidade: 'São Luís - MA', uf: 'MA', tipo: 'Outro' },

    // ─── MINAS GERAIS (MG) ──────────────────────────────────────────────────────
    { nome: 'Diagnóstico Hospital Imesa', endereco: 'Rua Adolfo Engel, 19 - Jardim Tropical', cidade: 'Alfenas - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Imesa', endereco: 'Rua Adolfo Engel, 19 - Jardim Tropical', cidade: 'Alfenas - MG', uf: 'MG', tipo: 'Hospital' },
    { nome: 'Ambulatório do Hospital Octaviano Neves', endereco: 'Rua Domingos Vieira, 561 - Santa Efigênia', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Clínica e Diagnóstico Barreiro', endereco: 'Av. Sinfrônio Brochado, 587 - Barreiro', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Clínica e Diagnóstico Minerva', endereco: 'Rua dos Aimorés, 3000 - Barro Preto', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Clínica Mais Saúde Santa Efigênia', endereco: 'Avenida do Contorno, 2001 - Santa Efigênia', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Venda Nova', endereco: 'Rua Dr. Álvaro Camargos, 2002 - São João Batista', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Diagnóstico Barreiro', endereco: 'Av. Sinfrônio Brochado, 587 - Barreiro', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Hospital Octaviano Neves', endereco: 'Rua Ceará, 186 - Santa Efigênia', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Hospital Vera Cruz', endereco: 'Rua Paracatu, 724 - Santo Agostinho', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Minerva', endereco: 'Rua dos Aimorés, 3000 - Barro Preto', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Pronto Atendimento Contorno', endereco: 'Avenida do Contorno, 2001', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Raja Gabaglia', endereco: 'Avenida Raja Gabaglia, 4091 - Santa Lúcia', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Timbiras', endereco: 'Rua dos Timbiras, 3210 - Barro Preto', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Venda Nova', endereco: 'Rua Dr. Álvaro Camargos, 2002 - São João Batista', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Octaviano Neves', endereco: 'Rua Ceará, 186 - Santa Efigênia', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Hospital' },
    { nome: 'Hospital Lifecenter BH', endereco: 'Av. do Contorno, 4747 - Funcionários', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Hospital' },
    { nome: 'Hospital Vera Cruz', endereco: 'Av. Barbacena, 653 - Barro Preto', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Hospital' },
    { nome: 'Pronto Atendimento Hospital Vera Cruz', endereco: 'Rua Paracatu, 724 - Santo Agostinho', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Santa Efigênia', endereco: 'Avenida do Contorno, 2001 - Santa Efigênia', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Outro' },
    { nome: 'Unidade de Autorização e Biometria BH', endereco: 'Rua Timbiras, 3156, Térreo - Barro Preto', cidade: 'Belo Horizonte - MG', uf: 'MG', tipo: 'Outro' },
    { nome: 'Unidade Avançada Betim', endereco: 'Av. Edméia Matos Lazzarotti, 2192 - Jardim da Cidade', cidade: 'Betim - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Unidade de Autorização e Biometria Betim', endereco: 'Avenida Edméia Matos Lazzarotti, 2192 - Jardim da Cidade', cidade: 'Betim - MG', uf: 'MG', tipo: 'Outro' },
    { nome: 'Centro Médico Proclin Eldorado', endereco: 'Av. João Cesar de Oliveira, 1009 - Eldorado', cidade: 'Contagem - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Diagnóstico Lifecenter Contagem', endereco: 'Rua das Mangueiras, 99 - Eldorado', cidade: 'Contagem - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Hospital Lifecenter Contagem', endereco: 'Rua das Mangueiras, 99 - Eldorado', cidade: 'Contagem - MG', uf: 'MG', tipo: 'Hospital' },
    { nome: 'Hospital e Maternidade Santa Mônica', endereco: 'Rua Pedro Ferreira do Amaral, 33 - Padre Libério', cidade: 'Divinópolis - MG', uf: 'MG', tipo: 'Hospital' },
    { nome: 'Bioimagem Hospital Santa Mônica', endereco: 'Rua Pedro F. Amaral, 33 - Padre Libério', cidade: 'Divinópolis - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Clínica Ituiutaba', endereco: 'Rua Vinte e Seis, 1547 - Centro', cidade: 'Ituiutaba - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Clínica Nova Ponte', endereco: 'Rua Olindino Soares, 913 - Centro', cidade: 'Nova Ponte - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Diagnóstico Hospital Poços de Caldas', endereco: 'Rua Frei Cristóvão Figueiredo, 125 - Jardim Esmeralda', cidade: 'Poços de Caldas - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Poços de Caldas', endereco: 'Rua Frei Cristóvão Figueiredo, 125 - Jardim Esmeralda', cidade: 'Poços de Caldas - MG', uf: 'MG', tipo: 'Hospital' },
    { nome: 'Unidade de Atendimento Poços de Caldas', endereco: 'Rua Frei Cristóvão Figueiredo, 125, 2° andar - Jardim Esmeralda', cidade: 'Poços de Caldas - MG', uf: 'MG', tipo: 'Outro' },
    { nome: 'Clínica Uberaba', endereco: 'Avenida Santa Beatriz da Silva, 1880 - Santa Maria', cidade: 'Uberaba - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Coleta Uberaba', endereco: 'Rua Ituiutaba, 577 - São Benedito', cidade: 'Uberaba - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Santa Maria', endereco: 'Avenida Santos Dumont, 2140 - Santa Maria', cidade: 'Uberaba - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Uberaba', endereco: 'Avenida Santa Beatriz da Silva, 1861 - São Benedito', cidade: 'Uberaba - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Santa Maria', endereco: 'Avenida Santos Dumont, 2140 - Santa Maria', cidade: 'Uberaba - MG', uf: 'MG', tipo: 'Outro' },
    { nome: 'Unidade de Autorização e Biometria Uberaba', endereco: 'Avenida Santa Beatriz, 1910 - Santa Maria', cidade: 'Uberaba - MG', uf: 'MG', tipo: 'Outro' },
    { nome: 'Clínica Marechal Deodoro', endereco: 'Rua Marechal Deodoro, 11 - General Osório', cidade: 'Uberlândia - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Clínica Uberlândia', endereco: 'Rua Virgílio Melo Franco, 465 - Maracanã', cidade: 'Uberlândia - MG', uf: 'MG', tipo: 'Clínica' },
    { nome: 'Coleta Uberlândia', endereco: 'Rua Virgílio Melo Franco, 465 - Maracanã', cidade: 'Uberlândia - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Diagnóstico Hospital Madrecor', endereco: 'Avenida Francisco Ribeiro, 1111 - Santa Mônica', cidade: 'Uberlândia - MG', uf: 'MG', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Madrecor', endereco: 'Avenida Francisco Ribeiro, 1111 - Santa Mônica', cidade: 'Uberlândia - MG', uf: 'MG', tipo: 'Hospital' },
    { nome: 'Unidade de Autorização e Biometria Uberlândia', endereco: 'Rua Marechal Deodoro, 11 - Centro', cidade: 'Uberlândia - MG', uf: 'MG', tipo: 'Outro' },
    { nome: 'Hospital e Maternidade Varginha', endereco: 'Av. Antonieta Ésper Kalas - Parque Mariela', cidade: 'Varginha - MG', uf: 'MG', tipo: 'Hospital' },

    // ─── MATO GROSSO DO SUL (MS) ────────────────────────────────────────────────
    { nome: 'Clínica Jardim dos Estados', endereco: 'Rua Antônio Maria Coelho, 2926 - Jardim dos Estados', cidade: 'Campo Grande - MS', uf: 'MS', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Carandá Bosque', endereco: 'Av. Mato Grosso, 5151, 1º andar - Carandá Bosque', cidade: 'Campo Grande - MS', uf: 'MS', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Dom Aquino', endereco: 'Rua Dom Aquino, 1682 - Amambai', cidade: 'Campo Grande - MS', uf: 'MS', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Campo Grande', endereco: 'Rua Dom Aquino, 2274 - Centro', cidade: 'Campo Grande - MS', uf: 'MS', tipo: 'Diagnóstico' },
    { nome: 'Unidade de Biometria Jardim dos Estados', endereco: 'Rua Antônio Maria Coelho, 2926 - Jardim dos Estados', cidade: 'Campo Grande - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Unidade de Autorização Chapadão do Sul', endereco: 'Av. 4, 541, Sala 04 - Centro', cidade: 'Chapadão do Sul - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Unidade de Autorização Deodápolis', endereco: 'Av. Francisco Alves da Silva, 611 - Centro', cidade: 'Deodápolis - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Dourados', endereco: 'Rua Ciro Melo, 1470 - Jardim Central', cidade: 'Dourados - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Dourados II', endereco: 'Avenida Presidente Vargas, 2145 - Cohafaba III Plano', cidade: 'Dourados - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Dourados', endereco: 'Rua Ciro Mello, 1470 - Jardim Central', cidade: 'Dourados - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Inocência', endereco: 'Rua João Batista Parreira, 539 - Centro', cidade: 'Inocência - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Ivinhema', endereco: 'Av. Brasil, 647 - Centro', cidade: 'Ivinhema - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Ivinhema', endereco: 'Av. Brasil, 647 - Centro', cidade: 'Ivinhema - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Sonora', endereco: 'Rua da Justiça, 103 - Centro', cidade: 'Sonora - MS', uf: 'MS', tipo: 'Outro' },
    { nome: 'Clínica Guarani', endereco: 'Av. Cap. Olinto Mancini, 2560 - Centro', cidade: 'Três Lagoas - MS', uf: 'MS', tipo: 'Clínica' },
    { nome: 'Unidade de Autorização e Biometria Três Lagoas', endereco: 'Av. Capitão Olinto Mancini, 2560 - Centro', cidade: 'Três Lagoas - MS', uf: 'MS', tipo: 'Outro' },

    // ─── MATO GROSSO (MT) ───────────────────────────────────────────────────────
    { nome: 'Unidade de Autorização Bosque da Saúde', endereco: 'Av. Historiador Rubens de Mendonça, 1856 - Bosque da Saúde', cidade: 'Cuiabá - MT', uf: 'MT', tipo: 'Outro' },
    { nome: 'Diagnóstico Jardim Guanabara', endereco: 'Rua Fernando Corrêa da Costa, 2256 - Jardim Guanabara', cidade: 'Rondonópolis - MT', uf: 'MT', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Rondonópolis', endereco: 'Rua Agostinho de Figueiredo, 60 - Jardim Guanabara', cidade: 'Rondonópolis - MT', uf: 'MT', tipo: 'Outro' },
    { nome: 'Unidade de Autorização e Biometria Vila Marinópolis', endereco: 'Rua Fernando Correa da Costa, 1538 - Vila Marinópolis', cidade: 'Rondonópolis - MT', uf: 'MT', tipo: 'Outro' },

    // ─── PARÁ (PA) ──────────────────────────────────────────────────────────────
    { nome: 'Central de Atendimento Belém', endereco: 'Tv. Mauriti, 2736 - Marco', cidade: 'Belém - PA', uf: 'PA', tipo: 'Outro' },
    { nome: 'Clínica Augusto Montenegro', endereco: 'Rodovia Augusto Montenegro Km5, 55 - Parque Verde', cidade: 'Belém - PA', uf: 'PA', tipo: 'Clínica' },
    { nome: 'Clínica Batista Campos', endereco: 'Travessa Padre Eutíquio, 1983', cidade: 'Belém - PA', uf: 'PA', tipo: 'Clínica' },
    { nome: 'Clínica Conselheiro', endereco: 'Avenida Conselheiro Furtado, 1885 - Cremação', cidade: 'Belém - PA', uf: 'PA', tipo: 'Clínica' },
    { nome: 'Clínica Lomas Valentinas', endereco: 'Travessa Lomás Valentina, 1140', cidade: 'Belém - PA', uf: 'PA', tipo: 'Clínica' },
    { nome: 'Clínica Marco', endereco: 'Avenida Rômulo Maiorana, 1662 - Marco', cidade: 'Belém - PA', uf: 'PA', tipo: 'Clínica' },
    { nome: 'Clínica Mundurucus', endereco: 'Rua dos Mundurucus, 2313 - Batista Campos', cidade: 'Belém - PA', uf: 'PA', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Hospital RioMar', endereco: 'Travessa Antônio Baena, 527 - Marco', cidade: 'Belém - PA', uf: 'PA', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Lomas', endereco: 'Tv. Lomas Valentina, 1186', cidade: 'Belém - PA', uf: 'PA', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Nazaré', endereco: 'Av. Alcindo Cacela, 1581 - Nazaré', cidade: 'Belém - PA', uf: 'PA', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Rio Mar', endereco: 'Travessa Antônio Baena, 527 - Marco', cidade: 'Belém - PA', uf: 'PA', tipo: 'Hospital' },
    { nome: 'Hospital Layr Maia', endereco: 'Av. Alcindo Cacela, 1581 - Nazaré', cidade: 'Belém - PA', uf: 'PA', tipo: 'Hospital' },
    { nome: 'Laboratório Batista Campos', endereco: 'Tv. Padre Eutíquio, 1983', cidade: 'Belém - PA', uf: 'PA', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Ananindeua', endereco: 'BR 316 - Km 2, 90 - Guanabara', cidade: 'Belém - PA', uf: 'PA', tipo: 'Outro' },
    { nome: 'Unidade de Autorização e Cadastro Pedreira', endereco: 'Travessa Lomas Valentina, 1176 - Pedreira', cidade: 'Belém - PA', uf: 'PA', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Pedreira', endereco: 'Travessa Lomas Valentina, 1140 - Pedreira', cidade: 'Belém - PA', uf: 'PA', tipo: 'Outro' },
    { nome: 'Clínica Rio Azul', endereco: 'Rua H, 248 - União', cidade: 'Parauapebas - PA', uf: 'PA', tipo: 'Clínica' },
    { nome: 'Hospital das Clínicas e Maternidade de Parauapebas', endereco: 'Rua H, 248 - União', cidade: 'Parauapebas - PA', uf: 'PA', tipo: 'Hospital' },

    // ─── PARAÍBA (PB) ───────────────────────────────────────────────────────────
    { nome: 'Clínica Campinense', endereco: 'Rua Doutor Severino Ribeiro Cruz, 277 - Centro', cidade: 'Campina Grande - PB', uf: 'PB', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnósticos Centro', endereco: 'Rua Doutor Severino Ribeiro Cruz, 277 - Centro', cidade: 'Campina Grande - PB', uf: 'PB', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Campinense', endereco: 'Rua Severino Ribeiro Cruz, 265 - Centro', cidade: 'Campina Grande - PB', uf: 'PB', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Centro Campina Grande', endereco: 'Rua Doutor Severino Ribeiro Cruz, 277 - Centro', cidade: 'Campina Grande - PB', uf: 'PB', tipo: 'Outro' },
    { nome: 'Unidade de Biometria e Autorização Campina Grande', endereco: 'Rua Severino Cruz, 277 - Centro', cidade: 'Campina Grande - PB', uf: 'PB', tipo: 'Outro' },
    { nome: 'Unidade de Cadastro Campina Grande', endereco: 'Rua Doutor Severino Cruz, 265 - Centro', cidade: 'Campina Grande - PB', uf: 'PB', tipo: 'Outro' },
    { nome: 'Centro Diagnóstico por Imagem João Pessoa', endereco: 'Av. Júlia Freire, 1058 - Expedicionários', cidade: 'João Pessoa - PB', uf: 'PB', tipo: 'Diagnóstico' },
    { nome: 'Clínica Ariano Suassuna', endereco: 'Av. Presidente Epitácio Pessoa, 3160 - Tambauzinho', cidade: 'João Pessoa - PB', uf: 'PB', tipo: 'Clínica' },
    { nome: 'Clínica João Pessoa', endereco: 'Rua Treze de Maio, 73 - Centro', cidade: 'João Pessoa - PB', uf: 'PB', tipo: 'Clínica' },
    { nome: 'Hospital e Maternidade da Paraíba', endereco: 'Av. Júlia Freire, 1058 - Expedicionários', cidade: 'João Pessoa - PB', uf: 'PB', tipo: 'Hospital' },
    { nome: 'Laboratório Expedicionários', endereco: 'Avenida Júlia Freire, 1058 - Expedicionários', cidade: 'João Pessoa - PB', uf: 'PB', tipo: 'Diagnóstico' },
    { nome: 'Unidade de Autorização, Cadastro e Biometria Expedicionários', endereco: 'Avenida Júlia Freire, 1058 - Expedicionários', cidade: 'João Pessoa - PB', uf: 'PB', tipo: 'Outro' },

    // ─── PERNAMBUCO (PE) ────────────────────────────────────────────────────────
    { nome: 'Clínica Cabo', endereco: 'Av. Pres. Vargas, 428 - Centro', cidade: 'Cabo de Santo Agostinho - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Centro Cabo', endereco: 'Av. Presidente Vargas, 428 - Centro', cidade: 'Cabo de Santo Agostinho - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Hospital do Cabo', endereco: 'Av. Pres. Vargas, 428 - Centro', cidade: 'Cabo de Santo Agostinho - PE', uf: 'PE', tipo: 'Hospital' },
    { nome: 'Laboratório Centro Cabo', endereco: 'Av. Presidente Vargas, 428 - Centro', cidade: 'Cabo de Santo Agostinho - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Cabo', endereco: 'Av. Pres. Vargas, 428 - Centro', cidade: 'Cabo de Santo Agostinho - PE', uf: 'PE', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Cabo', endereco: 'Avenida Presidente Vargas, 428', cidade: 'Cabo de Santo Agostinho - PE', uf: 'PE', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Goiana', endereco: 'Av. Marechal Deodoro da Fonseca, 234 - Centro', cidade: 'Goiana - PE', uf: 'PE', tipo: 'Outro' },
    { nome: 'Clínica Piedade', endereco: 'Av. Bernardo Vieira de Melo, 788 - Piedade', cidade: 'Jaboatão dos Guararapes - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Duarte Coelho', endereco: 'Av. Pres. Getúlio Vargas, 1351 - Bairro Novo', cidade: 'Olinda - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Olinda', endereco: 'Av. Getúlio Vargas, 514 - Bairro Novo', cidade: 'Olinda - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Unidade de Fisioterapia Olinda', endereco: 'Av. Getúlio Vargas, 481 - Bairro Novo', cidade: 'Olinda - PE', uf: 'PE', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Paulista', endereco: 'Rua Epitácio Pessoa, 231 - Centro', cidade: 'Paulista - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Paulista', endereco: 'Rua Milton de Souza Lopes, 84 - Centro', cidade: 'Paulista - PE', uf: 'PE', tipo: 'Outro' },
    { nome: 'Clínica Barão de Itamaracá', endereco: 'Rua Barão de Itamaracá, 142 - Espinheiro', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Centro de Diagnóstico por Imagem Boa Vista', endereco: 'Rua Edson Álvares, 370 - Casa Forte', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Clínica Boa Viagem', endereco: 'Rua Dálhia, 95 - Setúbal', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Boa Vista', endereco: 'Avenida Manoel Borba, 737 - Boa Vista', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Casa Forte', endereco: 'Rua Edson Álvares, 370 - Casa Forte', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Conselheiro Aguiar', endereco: 'Av. Conselheiro Aguiar, 3763 - Boa Viagem', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Epaminondas', endereco: 'Rua Epaminondas de Melo, 177 - Derby', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Espinheiro', endereco: 'R. Dr. José Luiz da Silveira Barros, 122 - Espinheiro', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Graças', endereco: 'Rua da Hora, 543 - Espinheiro', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Mário Domingues', endereco: 'R. Mário Domingues, 152 - Boa Vista', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Pedro da Hora', endereco: 'Rua da Hora, 366 - Espinheiro', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Recife', endereco: 'Rua do Espinheiro, 119 - Espinheiro', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Clínica Zona Sul', endereco: 'Rua João Cardoso Aires, 647 - Setúbal', cidade: 'Recife - PE', uf: 'PE', tipo: 'Clínica' },
    { nome: 'Fisioterapia Parque Amorim', endereco: 'Rua Fernandes Vieira, 675 - Boa Vista', cidade: 'Recife - PE', uf: 'PE', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Zona Sul', endereco: 'Rua João Cardoso Aires, 647 - Setúbal', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnósticos Casa Forte', endereco: 'Rua Edson Álvares, 370 - Casa Forte', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnósticos Iputinga', endereco: 'Av. Prof. Moraes Rego, 314 - Iputinga', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Hospital Ariano Suassuna', endereco: 'Av. Gov. Agamenon Magalhães, 4623 - Ilha do Leite', cidade: 'Recife - PE', uf: 'PE', tipo: 'Hospital' },
    { nome: 'Hospital Capibaribe', endereco: 'Rua Paissandu, 767 - Boa Vista', cidade: 'Recife - PE', uf: 'PE', tipo: 'Hospital' },
    { nome: 'Hospital Casa Forte', endereco: 'Rua Edson Álvares, 370 - Casa Forte', cidade: 'Recife - PE', uf: 'PE', tipo: 'Hospital' },
    { nome: 'Hospital e Maternidade Vasco Lucena', endereco: 'Rua do Progresso, 47 - Boa Vista', cidade: 'Recife - PE', uf: 'PE', tipo: 'Hospital' },
    { nome: 'Hospital Ilha do Leite', endereco: 'Rua Dr. João Asfora, 35 - Ilha do Leite', cidade: 'Recife - PE', uf: 'PE', tipo: 'Hospital' },
    { nome: 'Hospital Mandacaru', endereco: 'Avenida Gov. Agamenon Magalhães, 3621 - Torreão', cidade: 'Recife - PE', uf: 'PE', tipo: 'Hospital' },
    { nome: 'Laboratório Agamenon Magalhães', endereco: 'Av. Agamenon Magalhães, 107 - Boa Vista', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Laboratório Boa Vista', endereco: 'Rua Paissandu, 767 - Boa Vista', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Laboratório Caxangá', endereco: 'Av. Prof. Moraes Rego, 314 - Iputinga', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Laboratório Centro Recife', endereco: 'Rua Milton de Souza Lopes, 84 - Centro', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Laboratório Ilha do Leite', endereco: 'Rua Dr. João Asfora, 65 - Ilha do Leite', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Laboratório Paissandú', endereco: 'Rua do Paissandú, 738 - Boa Vista', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Laboratório Parque Amorim', endereco: 'Rua Fernandes Vieira, 699 - Boa Vista', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },
    { nome: 'Laboratório Zona Sul', endereco: 'Rua João Cardoso Aires, 647 - Boa Viagem', cidade: 'Recife - PE', uf: 'PE', tipo: 'Diagnóstico' },

    // ─── PIAUÍ (PI) ─────────────────────────────────────────────────────────────
    { nome: 'Clínica Teresina', endereco: 'Av. Honório de Paiva, 383 - Primeiro Piso - Centro', cidade: 'Teresina - PI', uf: 'PI', tipo: 'Clínica' },
    { nome: 'Hospital e Maternidade Rio Poty', endereco: 'Rua Lucídio Freitas, 2070 - Marquês de Paranaguá', cidade: 'Teresina - PI', uf: 'PI', tipo: 'Hospital' },

    // ─── RIO GRANDE DO NORTE (RN) ───────────────────────────────────────────────
    { nome: 'Clínica Rodolfo Fernandes', endereco: 'Avenida Diocesana, 260 - Nova Betânia', cidade: 'Mossoró - RN', uf: 'RN', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnósticos Hospital Celina Guimarães', endereco: 'Rua Eduardo Medeiros, 284 - Nova Betânia', cidade: 'Mossoró - RN', uf: 'RN', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Celina Guimarães', endereco: 'Rua Eduardo Medeiros, 284 - Nova Betânia', cidade: 'Mossoró - RN', uf: 'RN', tipo: 'Hospital' },
    { nome: 'Unidade de Autorização e Biometria Mossoró', endereco: 'Avenida Augusto Severo, 273 - Centro', cidade: 'Mossoró - RN', uf: 'RN', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Mossoró', endereco: 'Av. Diocesana, 260 - Nova Betânia', cidade: 'Mossoró - RN', uf: 'RN', tipo: 'Outro' },
    { nome: 'Unidade de Cadastro Mossoró', endereco: 'Avenida Alberto Maranhão, 1505 - Centro', cidade: 'Mossoró - RN', uf: 'RN', tipo: 'Outro' },
    { nome: 'Clínica Complexo Alecrim', endereco: 'Rua Presidente Quaresma, 967 - Alecrim', cidade: 'Natal - RN', uf: 'RN', tipo: 'Clínica' },
    { nome: 'Clínica Complexo Alecrim II', endereco: 'Rua Presidente Quaresma, 967 - Alecrim', cidade: 'Natal - RN', uf: 'RN', tipo: 'Clínica' },
    { nome: 'Clínica Nascimento Castro', endereco: 'Av. Nascimento Castro, 1764 - Lagoa Seca', cidade: 'Natal - RN', uf: 'RN', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Alecrim', endereco: 'Rua Presidente Quaresma, 1137 - Alecrim', cidade: 'Natal - RN', uf: 'RN', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnósticos Hospital Natal', endereco: 'Av. Nascimento de Castro, 1764 - Lagoa Seca', cidade: 'Natal - RN', uf: 'RN', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Natal', endereco: 'Av. Nascimento de Castro, 1764 - Lagoa Seca', cidade: 'Natal - RN', uf: 'RN', tipo: 'Hospital' },
    { nome: 'Laboratório Complexo Alecrim', endereco: 'Rua Presidente Quaresma, 967 - Alecrim', cidade: 'Natal - RN', uf: 'RN', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Alecrim', endereco: 'Rua Presidente Quaresma, 967 - Alecrim', cidade: 'Natal - RN', uf: 'RN', tipo: 'Outro' },
    { nome: 'Unidade de Autorização, Cadastro e Biometria Natal', endereco: 'Rua Presidente Quaresma, 1137 - Alecrim', cidade: 'Natal - RN', uf: 'RN', tipo: 'Outro' },

    // ─── RIO GRANDE DO SUL (RS) ─────────────────────────────────────────────────
    { nome: 'Clínica Bento Gonçalves', endereco: 'Rua Buarque de Macedo, 1555 - Centro', cidade: 'Bento Gonçalves - RS', uf: 'RS', tipo: 'Clínica' },
    { nome: 'Clínica Canoas', endereco: 'Rua Ipiranga, 135 - Centro', cidade: 'Canoas - RS', uf: 'RS', tipo: 'Clínica' },
    { nome: 'Clínica Caxias do Sul', endereco: 'Rua Sinimbu, 1767 - Centro', cidade: 'Caxias do Sul - RS', uf: 'RS', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Pelotas', endereco: 'Rua Almirante Barroso, 1251 - Centro', cidade: 'Pelotas - RS', uf: 'RS', tipo: 'Diagnóstico' },
    { nome: 'Clínica Porto Alegre Centro', endereco: 'Rua dos Andradas, 1505 - Centro Histórico', cidade: 'Porto Alegre - RS', uf: 'RS', tipo: 'Clínica' },
    { nome: 'Clínica Porto Alegre Zona Norte', endereco: 'Av. Assis Brasil, 5680 - Sarandi', cidade: 'Porto Alegre - RS', uf: 'RS', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Porto Alegre', endereco: 'Av. Alberto Bins, 514 - Centro Histórico', cidade: 'Porto Alegre - RS', uf: 'RS', tipo: 'Diagnóstico' },
    { nome: 'Hospital Cristo Redentor', endereco: 'Rua Domingos Rubbo, 20 - Cristo Redentor', cidade: 'Porto Alegre - RS', uf: 'RS', tipo: 'Hospital' },
    { nome: 'Unidade de Biometria Porto Alegre', endereco: 'Rua dos Andradas, 1505 - Centro Histórico', cidade: 'Porto Alegre - RS', uf: 'RS', tipo: 'Outro' },

    // ─── SANTA CATARINA (SC) ────────────────────────────────────────────────────
    { nome: 'Clínica Blumenau', endereco: 'Rua Sete de Setembro, 1451 - Centro', cidade: 'Blumenau - SC', uf: 'SC', tipo: 'Clínica' },
    { nome: 'Clínica Florianópolis Centro', endereco: 'Rua Conselheiro Mafra, 555 - Centro', cidade: 'Florianópolis - SC', uf: 'SC', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Florianópolis', endereco: 'Rua Conselheiro Mafra, 555 - Centro', cidade: 'Florianópolis - SC', uf: 'SC', tipo: 'Diagnóstico' },
    { nome: 'Clínica Joinville', endereco: 'Rua do Príncipe, 1161 - Centro', cidade: 'Joinville - SC', uf: 'SC', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Joinville', endereco: 'Rua do Príncipe, 1161 - Centro', cidade: 'Joinville - SC', uf: 'SC', tipo: 'Diagnóstico' },

    // ─── SÃO PAULO (SP) ─────────────────────────────────────────────────────────
    { nome: 'Clínica 9 de julho', endereco: 'R. Nove de Julho, 5 - Jardim Nova América', cidade: 'Araraquara - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Clínica Hospital Araraquara', endereco: 'Av. José Bonifácio, 569 - Centro', cidade: 'Araraquara - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Clínica Jardim Primavera', endereco: 'Av. Joaquim Alves, 58 - Jardim Primavera', cidade: 'Araraquara - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hospital e Maternidade Araraquara', endereco: 'Av. José Bonifácio, 569 - Centro', cidade: 'Araraquara - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Unidade de Biometria Araraquara', endereco: 'Rua Gonçalves Dias, 561, Shopping Lupo - 1º andar - Amadeu Furtado', cidade: 'Araraquara - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Clínico Arujá', endereco: 'Av. João Manoel, S/N - Centro Histórico', cidade: 'Arujá - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Arujá', endereco: 'Al. Nassima Jorge Miguel, 70 - Center Ville', cidade: 'Arujá - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Unidade de Biometria Assis', endereco: 'Rua Victor C. Romano, 97, Sala 01 - Jardim Europa', cidade: 'Assis - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Pronto Atendimento Barra Bonita', endereco: 'R. Manoel D Almeida Camargo, 135 - Vila Operaria', cidade: 'Barra Bonita - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Barra Bonita', endereco: "Rua Manoel D'Almeida Camargo, 135 - Vila Operária", cidade: 'Barra Bonita - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Jardim Alvorada', endereco: 'Av. Quarenta e Três, 780 - Jardim Alvorada', cidade: 'Barretos - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento de Barretos', endereco: 'Av. Eng. Necker Carvalho de Camargo, 1701 - América', cidade: 'Barretos - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Barretos', endereco: 'Av. 43, 780 - Jardim Alvorada', cidade: 'Barretos - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Clínico Alphaville', endereco: 'Alameda Amazonas, 329 - Alphaville Industrial', cidade: 'Barueri - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Alphaville', endereco: 'Alameda Amazonas, 329 - Alphaville Industrial', cidade: 'Barueri - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Barueri', endereco: 'Rua Campos Sales, 118 - Centro', cidade: 'Barueri - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Clínica Diagnóstico Rio Branco', endereco: 'Rua Rio Branco, 12-40 - Centro', cidade: 'Bauru - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Clínica Rodrigues de Abreu', endereco: 'Praça Rodrigues de Abreu, 338 - Centro', cidade: 'Bauru - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Nações Unidas', endereco: 'Av. Nações Unidas, 17-27 - Vila Santo Antônio', cidade: 'Bauru - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Rio Branco', endereco: 'Rua Gustavo Maciel, 15-15 - Centro', cidade: 'Bauru - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hospital Bauru', endereco: 'Rua Agenor Meira, 11-27 - Centro', cidade: 'Bauru - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Hospital e Maternidade Bauru', endereco: 'Rua Gustavo Maciel, 15 - Centro', cidade: 'Bauru - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Unidade de Biometria Bauru', endereco: 'Av. Nações Unidas, 17-27 - Vila Santo Antônio', cidade: 'Bauru - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Clínico Caieiras', endereco: 'R. Ambrosina do Carmo Buonaguide, 157/159 - Centro', cidade: 'Caieiras - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Polvilho', endereco: 'Avenida Tenente Marques, 1795 - Jardim São Luiz', cidade: 'Cajamar - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Polvilho', endereco: 'Av. Ten. Marques, 1795 - Jardim São Luiz', cidade: 'Cajamar - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Cajuru', endereco: 'Rua Major Palma, 410, Sala 08 - Centro', cidade: 'Cajuru - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Centro Clínico Andrade Neves I', endereco: 'Rua Marechal Deodoro, 134 - Centro', cidade: 'Campinas - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Andrade Neves II', endereco: 'Av. Andrade Neves, 1300 - Centro', cidade: 'Campinas - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Itapura', endereco: 'Av. Barão de Itapura, 2642 - Jardim Guanabara', cidade: 'Campinas - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Clínica e Diagnóstico Campinas', endereco: 'Av. João Jorge, 370 - Vila Industrial', cidade: 'Campinas - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Campinas', endereco: 'Rua Prefeito Passos, 295 - Jardim Guanabara', cidade: 'Campinas - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Renascença de Campinas', endereco: 'Av. Barão de Itapura, 1444 - Jardim Guanabara', cidade: 'Campinas - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Qualivida Campinas', endereco: 'Av. Barão de Itapura, 1356 - Vila Itapura', cidade: 'Campinas - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Clínica Vila Santa – Clínica Capivari', endereco: 'Av. Brigadeiro Faria Lima, 40 - Bela Vista', cidade: 'Capivari - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Pronto Atendimento Capivari', endereco: 'Praça Dr. Mário Dias de Aguiar, 1 - Centro', cidade: 'Capivari - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Capivari', endereco: 'Praça Mario Dias Aguiar, 01 - Centro', cidade: 'Capivari - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Clínico Carapicuíba', endereco: 'Avenida Tâmara, 311 - Centro', cidade: 'Carapicuíba - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Carapicuíba', endereco: 'Rua Atílio Tolaine, altura nº 30 - Av. Tâmara, 311', cidade: 'Carapicuíba - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Centro Clínico Jundiaí', endereco: 'Rua São Bento, 41 - Centro', cidade: 'Jundiaí - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Oftalmológico de Jundiaí', endereco: 'Rua São Bento, 41 - Centro', cidade: 'Jundiaí - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Espaço Notrelife 50+ Jundiaí', endereco: 'Rua São Bento, 41 - Centro', cidade: 'Jundiaí - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Jundiaí', endereco: 'R. São Bento, 41 - Centro', cidade: 'Jundiaí - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Paulo Sacramento', endereco: 'R. Quinze de Novembro, 865 - Centro', cidade: 'Jundiaí - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Qualivida Jundiaí', endereco: 'Rua São Bento, 41 - Centro', cidade: 'Jundiaí - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hospital e Maternidade Lins', endereco: 'Av. Nicolau Zarvos, 1640 - Jardim Aeroporto', cidade: 'Lins - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Unidade de Biometria Lins', endereco: 'Rua Pedro de Toledo, 265 - Centro', cidade: 'Lins - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Clínica Santa Rita', endereco: 'Rua Duque de Caxias, 341 - Centro', cidade: 'Santa Rita do Passa Quatro - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Unidade de Biometria Santa Rita do Passa Quatro', endereco: 'Rua Inácio Ribeiro, 423 - Centro', cidade: 'Santa Rita do Passa Quatro - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Monte Alto', endereco: 'Rua Bahia, 133 - Jardim Boa Vista', cidade: 'Santa Rosa de Viterbo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento Santa Rosa', endereco: 'R. Dr. Mario Carneiro da Cunha, 949 - Monte Alto', cidade: 'Santa Rosa de Viterbo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Santa Rosa de Viterbo', endereco: 'Rua Mario Carneiro da Cunha, 949 - Monte Alto', cidade: 'Santa Rosa de Viterbo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Clínico IPSA', endereco: 'Rua Prefeito Justino Paixão, 85 - Centro', cidade: 'Santo André - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Santa Paula', endereco: 'Av. Doutor Augusto De Toledo, 540 - Santa Paula', cidade: 'Santo André - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Santo André 2', endereco: 'Avenida Dom Pedro II, 2213 - Bairro Jardim', cidade: 'Santo André - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Santo André 3', endereco: 'Rua General Glicério, 477 - Centro', cidade: 'Santo André - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Diagnóstico Santo André - Adhemar de Barros', endereco: 'Rua Gertrudes de Lima, 771 - Vila Assunção', cidade: 'Santo André - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Santo André - XV de Novembro', endereco: 'Av. Quinze de Novembro, 512 - Centro', cidade: 'Santo André - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Espaço Notrelife 50+ ABC', endereco: 'Rua Gertrudes de Lima, 771 - Vila Assunção', cidade: 'Santo André - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Unidade Avançada Santo André', endereco: 'R. Gertrudes de Lima, 771 - Vila Assunção', cidade: 'Santo André - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Clínico Frei Galvão - Unidade Santos', endereco: 'Rua Doutor Heitor de Moraes, 15 - Boqueirão', cidade: 'Santos - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Santos', endereco: 'Rua Dr. Heitor de Moraes, 15 - Boqueirão', cidade: 'Santos - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hospital Frei Galvão', endereco: 'Rua Dr. Heitor de Moraes, 19/23 - Boqueirão', cidade: 'Santos - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Qualivida - Baixada Santista', endereco: 'Rua Doutor Heitor de Moraes, 19 - Boqueirão', cidade: 'Santos - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'CASE - ABC', endereco: 'Rua Bering, 71 A - Jardim do Mar', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Clínico São Bernardo 1', endereco: 'Rua Paulo Kruger, 68 - Centro', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico São Bernardo 3', endereco: 'Rua General Osório, 245/247 - Centro', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico São Bernardo 4', endereco: 'Rua Armando Sales de Oliveira, 120 - Centro', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro de Oncologia ABC', endereco: 'Avenida Lucas Nogueira Garcez, 442 - Centro', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Médico ABC', endereco: 'Avenida Francisco Prestes Maia, 1547 - Centro', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Oftalmológico Hapvida', endereco: 'Avenida Lucas Nogueira Garcez, 735 - Centro', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico SBC - Prestes Maia', endereco: 'Avenida Prestes Maia, 1547 - Centro', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico SBC - Lucas Garcéz', endereco: 'Avenida Lucas Nogueira Garcéz, 442 - Centro', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico SBC - Banda', endereco: 'Rua Banda, 44 - Jardim do Mar', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico SBC - Benedito Montenegro', endereco: 'Rua Benedito Montenegro, 52 - Centro', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade NotreCare ABC', endereco: 'Avenida Pereira Barreto, 846 - Baeta Neves', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Hospital Intermédica ABC', endereco: 'R. Aurélia Salazar Jorge, 303 - Rudge Ramos', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Hospital São Bernardo', endereco: 'Av. Lucas Nogueira Garcez, 400 - Jardim do Mar', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'NotreLabs São Bernardo do Campo - Atlântica', endereco: 'Rua Atlântica, 121 - Jardim do Mar', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Núcleo de Terapias Integradas ABC', endereco: 'Avenida Índico, 684 - Jardim do Mar', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Qualivida - ABC', endereco: 'Rua Banda, 37 - Jardim do Mar', cidade: 'São Bernardo do Campo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Médico São Caetano', endereco: 'Avenida Dr. Augusto de Toledo, 538 - Santa Paula', cidade: 'São Caetano do Sul - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Centro São Carlos', endereco: 'Rua Nove de Julho, 2075 - Centro', cidade: 'São Carlos - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento São Carlos', endereco: 'Rua Paulino Botelho de Abreu Sampaio, 800 - Jardim Bethânia', cidade: 'São Carlos - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Unidade de Biometria São Carlos', endereco: 'Rua Paulino Botelho de Abreu Sampaio, 800 - Jardim Bethânia', cidade: 'São Carlos - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hospital São José do Rio Preto', endereco: 'Av. Anísio Haddad, 7195 - Jardim Aclimação', cidade: 'São José do Rio Preto - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Clínica Centro Médico de Especialidades', endereco: 'Praça Elza Ferreira Rahal, 83 - Centro', cidade: 'São José dos Campos - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Clínica Pró Infância', endereco: 'Av. Eng. Francisco José Longo, 862 - Jardim São Dimas', cidade: 'São José dos Campos - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Acácias', endereco: 'Rua Taubaté, 101 - Vila Nair', cidade: 'São José dos Campos - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Vicentina Aranha', endereco: 'Avenida Nove de Julho, 331 - Jardim Apolo', cidade: 'São José dos Campos - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hospital Pró Infância - Pronto Atendimento', endereco: 'Av. Eng. Francisco José Longo, 862 - Jardim São Dimas', cidade: 'São José dos Campos - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'São José Saúde Unidade de Autorização', endereco: 'Praça Melvin Jones, 07 - Jardim São Dimas', cidade: 'São José dos Campos - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Unidade de Biometria São José dos Campos', endereco: 'Praça Melvin Jones, 7 - Jardim São Dimas', cidade: 'São José dos Campos - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Clínico Anália Franco', endereco: 'Rua Acuruí, 493 - Vila Formosa', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Barra Funda', endereco: 'Av. Francisco Matarazzo, 612 - Água Branca', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Belém', endereco: 'Rua Cesário Alvim, 174 - Belenzinho', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Itaquera', endereco: 'Av. Itaquera, 7426 - Vila Carmosina', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Lapa', endereco: 'R. George Smith, 287 - Lapa', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Pompeia', endereco: 'Av. Pompéia, 1165 - Perdizes', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Santana', endereco: 'Av. Cruzeiro do Sul, 2977 - Santana', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico São Miguel', endereco: 'Rua Tenente Luis Fernando Lobo, 51 - São Miguel Paulista', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Tatuapé', endereco: 'Rua Platina, 215 - Tatuapé', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Zona Norte', endereco: 'Av. Nova Cantareira, 229 - Tucuruvi', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Zona Oeste', endereco: 'R. Dr. Edson de Melo, 357 - Vila Maria', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Zona Sul', endereco: 'Avenida João Dias, 76/96 - Santo Amaro', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro de Fisioterapia - Higienópolis', endereco: 'R. São Vicente de Paulo, 463 - Santa Cecilia', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro de Oncologia São Paulo', endereco: 'Av. Angélica, 381 - Santa Cecilia', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Médico São Gabriel', endereco: 'Av. Amador Bueno da Veiga, 195 - Penha de França', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Clínica de Terapias Integradas Hospital Salvalus', endereco: 'Rua Hipódromo, 987 - Mooca', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Clínica Jaú', endereco: 'Rua Rangel Pestana, 917 - Centro', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Barra Funda', endereco: 'Av. Francisco Matarazzo, 612 - Água Branca', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Unidade Avançada Salvalus', endereco: 'Rua Hipódromo, 987 - Mooca', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Angélica', endereco: 'Avenida Angélica, 1045 - Higienópolis', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Angélica - Ressonância Magnética', endereco: 'Av. Angélica, 1.023 - Higienópolis', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Belém', endereco: 'Rua Cesário Alvim, 174 - Belenzinho', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Hermínio Lemos', endereco: 'Rua Hermínio Lemos, 385 - Cambuci', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Itaquera', endereco: 'R. Santa Cruz do Piauí, 17 - Itaquera', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Penha', endereco: 'Av. Amador Bueno da Veiga, 195 - Penha de França', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Santana', endereco: 'Av. Cruzeiro do Sul, 2977 - Santana', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Tatuapé - Bom Sucesso', endereco: 'R. Bom Sucesso, 348 - Cidade Mãe do Céu', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hapvida Diagnóstico Tatuapé - ICEM', endereco: 'R. Icém, 57 - Tatuapé', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hospital Bosque Saúde', endereco: 'Av. Bosque da Saúde, 1926 - Saúde', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Hospital e Maternidade Nossa Senhora do Rosário', endereco: 'R. Dr. Edson de Melo, 357 - Vila Maria', cidade: 'São Paulo - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Centro Clínico Frei Galvão - São Vicente', endereco: 'Avenida Presidente Wilson, 199 - Itararé', cidade: 'São Vicente - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Clínica Barão do Rio Branco', endereco: 'Rua Barão do Rio Branco, 2069 - Jardim Alexandre Balbo', cidade: 'Sertãozinho - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hospital Netto Campelo', endereco: 'R. Elpídio Gomes, 785 - Centro', cidade: 'Sertãozinho - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Unidade de Biometria Sertãozinho', endereco: 'Rua Barão do Rio Branco, 2069 - Jardim Lopes da Silva', cidade: 'Sertãozinho - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Clínico Itavuvu', endereco: 'Av. Itavuvu, 155 - Vila Olímpia', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Modelo', endereco: 'Rua Mauro Marques da Silva, 195 - Vila Trujillo', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Penha', endereco: 'R. Miranda Azevedo, 58 - Centro', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Rodrigues Pacheco', endereco: 'Rua Rodrigues Pacheco, 204 - Vila Amélia', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Trujillo I', endereco: 'Av. Dr. Armando Sales de Oliveira, 290 - Vila Trujillo', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Centro Clínico Trujillo II', endereco: 'Av. Dr. Armando Sales de Oliveira, 150 - Vila Trujillo', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Clínica Santa Clara', endereco: 'R. Santa Clara, 162 - Centro', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Espaço Notrelife 50+ Sorocaba', endereco: 'Rua Quinze de Novembro, 464 - Centro', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Ipanema', endereco: 'Avenida Ipanema, 532 - Vila Nova Sorocaba', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Modelo', endereco: 'R. Afonso Pedrazzi, 180 - Vila Trujillo', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Hospital NotreCare Sorocaba', endereco: 'R. Rodrigues Pacheco, 145 - Centro', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Qualivida Sorocaba', endereco: 'R. Domingos Fernandes, 198 - Vila Trujillo', cidade: 'Sorocaba - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Sumaré', endereco: 'Rua Máximo Biondo, 310 - Centro', cidade: 'Sumaré - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Centro Clínico Suzano', endereco: 'R. Nelson Pacheco, 663 - Centro', cidade: 'Suzano - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Hapvida Diagnóstico Suzano', endereco: 'Rua Campos Salles, 663 - Centro', cidade: 'Suzano - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Núcleo de Terapias Integradas Suzano', endereco: 'R. Nelson Pacheco, 663 - Centro', cidade: 'Suzano - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Centro Médico Taboão da Serra', endereco: 'Estrada São Francisco, 1200 - Jardim Henriqueta', cidade: 'Taboão da Serra - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Taboão da Serra', endereco: 'Estr. São Francisco, 1200 - Vila Sonia do Taboão', cidade: 'Taboão da Serra - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Hospital e Maternidade Family', endereco: 'Rua João Santucci, 270 - Vila Santa Luzia', cidade: 'Taboão da Serra - SP', uf: 'SP', tipo: 'Hospital' },
    { nome: 'Unidade de Biometria Tambaú', endereco: 'Rua Coronel Manoel de Souza Meireles, 20 - Centro', cidade: 'Tambaú - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Clínica Vargem Grande do Sul', endereco: 'Praça Nossa Senhora Aparecida, 61 - Nossa Sra. Aparecida', cidade: 'Vargem Grande do Sul - SP', uf: 'SP', tipo: 'Clínica' },
    { nome: 'Unidade de Biometria Vargem Grande do Sul', endereco: 'Praça Nossa Sra. Aparecida, 61 - Jardim Paraíso', cidade: 'Vargem Grande do Sul - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Hapvida Diagnóstico Várzea Paulista', endereco: 'Av. Fernão Dias Paes Leme, 1670 - Vila Santa Terezinha', cidade: 'Várzea Paulista - SP', uf: 'SP', tipo: 'Diagnóstico' },
    { nome: 'Pronto Atendimento de Viradouro', endereco: 'Rua do Hospital, 53 - Centro', cidade: 'Viradouro - SP', uf: 'SP', tipo: 'Outro' },
    { nome: 'Unidade de Biometria Viradouro', endereco: 'Rua do Hospital, 53 - Centro', cidade: 'Viradouro - SP', uf: 'SP', tipo: 'Outro' },
  ];

  const json = JSON.stringify(raw);
  const bytes = new TextEncoder().encode(json);
  const enc = new Uint8Array(bytes.length);
  for (let i = 0; i < bytes.length; i++) enc[i] = bytes[i] ^ _K[i % _K.length];
  let bin = '';
  for (let i = 0; i < enc.length; i++) bin += String.fromCharCode(enc[i]);
  return btoa(bin);
})();

// Lazy-decoded singleton
let _cache: HapvidaUnidade[] | null = null;

function getUnidades(): HapvidaUnidade[] {
  if (!_cache) _cache = _d(_P);
  return _cache;
}

// Public API — Proxy for lazy access
export const HAPVIDA_UNIDADES: HapvidaUnidade[] = new Proxy([] as HapvidaUnidade[], {
  get(_, prop) {
    const arr = getUnidades();
    if (prop === 'length') return arr.length;
    if (prop === Symbol.iterator) return arr[Symbol.iterator].bind(arr);
    if (prop === 'filter') return arr.filter.bind(arr);
    if (prop === 'map') return arr.map.bind(arr);
    if (prop === 'forEach') return arr.forEach.bind(arr);
    if (prop === 'find') return arr.find.bind(arr);
    if (prop === 'some') return arr.some.bind(arr);
    if (prop === 'every') return arr.every.bind(arr);
    if (prop === 'reduce') return arr.reduce.bind(arr);
    if (prop === 'slice') return arr.slice.bind(arr);
    if (typeof prop === 'string' && !isNaN(Number(prop))) return arr[Number(prop)];
    return (arr as any)[prop];
  }
});

// Mapa completo de siglas → nomes
const ALL_UF_LABELS: Record<string, string> = {
  AC: 'Acre', AL: 'Alagoas', AM: 'Amazonas', AP: 'Amapá', BA: 'Bahia',
  CE: 'Ceará', DF: 'Distrito Federal', ES: 'Espírito Santo', GO: 'Goiás',
  MA: 'Maranhão', MG: 'Minas Gerais', MS: 'Mato Grosso do Sul', MT: 'Mato Grosso',
  PA: 'Pará', PB: 'Paraíba', PE: 'Pernambuco', PI: 'Piauí', PR: 'Paraná',
  RJ: 'Rio de Janeiro', RN: 'Rio Grande do Norte', RO: 'Rondônia', RR: 'Roraima',
  RS: 'Rio Grande do Sul', SC: 'Santa Catarina', SE: 'Sergipe', SP: 'São Paulo', TO: 'Tocantins',
};

// Estados com unidades cadastradas
export const UFS_DISPONIVEIS = [...new Set(getUnidades().map(u => u.uf))].sort();

// UF_LABELS filtrado
export const UF_LABELS: Record<string, string> = Object.fromEntries(
  UFS_DISPONIVEIS.map(uf => [uf, ALL_UF_LABELS[uf] ?? uf])
);

export function getUnidadesPorUF(uf: string): HapvidaUnidade[] {
  return getUnidades().filter(u => u.uf === uf);
}
